In [1]:
import pandas as pd
import numpy as np

In [4]:
gs = pd.read_csv("IgnitionPrueba.csv", sep=",")

gs.head()

c:\Users\thygo\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (0,2,3,4,5,6,7,8,10,11,12,14,15,16,17) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,DOW,Time,Bay 1\Chiller Status,Bay 1\Temperature,Bay 1\Humidity,Bay 1\Power Draw,Bay 2\Chiller Status,Bay 2\Temperature,Bay 2\Humidity,Bay 2\Power Draw,Bay 3\Chiller Status,Bay 3\Temperature,Bay 3\Humidity,Bay 3\Power Draw,Bay 4\Chiller Status,Bay 4\Temperature,Bay 4\Humidity,Bay 4\Power Draw
0,Int32,String,Int32,Float,Float,Float,Int32,Float,Float,Float,Int32,Float,Float,Float,Int32,Float,Float,Float
1,1,12:00:00 AM,1,50,10,0,2,50,10,0,0,50,10,0,1,50,10,0
2,1,12:00:10 AM,2,49.017,9.045,0.09,2,50.891,10.203,0,1,50.032,10.73,0,2,49.807,10.71,1.005
3,1,12:00:20 AM,2,48.551,8.538,0,1,50.527,10.05,0,0,49.807,11.022,0,0,49.87,11.04,0
4,1,12:00:30 AM,1,49.523,8.208,0,1,49.67,10.134,2.195,1,50.613,11.003,0,1,50.029,11.755,875

In [ ]:
time = gs['Time']
status = gs['Bay 1\\Chiller Status']
temp = gs['Bay 1\\Chiller Temp']